apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: buildpack-admission
webhooks:
  - name: buildpack-admission.buildpack-admission.svc.toolsbeta.local
    clientConfig:
      service:
        name: buildpack-admission
        namespace: buildpack-admission
        path: "/"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXlNekE1TlRRMU5Gb1hEVEk1TVRBeU1EQTVOVFExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2xjCmJwK29lUlYrM1N2K3pYN1FsTVZSeVI2NnBPK1lPUTYwUVd0M0xxVUtRODRhQXpoVHJWek5NMmVxQ2IxWlZGUFMKTlRzczBwMTFUMUsrQzdVSndBRkFmOHV1RTlGNjFkVHpSMnNuT2ZmTUdDalZVT0txZEJucDNaTUlDMDhGOVlsagpndWc2bXQ5L1RFRGNML2RETDZpOEtQS1VmSC96cXdvUkpBUjVOUDVMelVPYVBrMzJxaUJqYjQ2UWVyZ3o3Z2VHCjQxOHRjTnc5aGsrZFBWMTdUdFRkUEg4NGQ5TlFaMnpDWGp5SnhaNnNWZlE0SDcyWml1cUFVbmx2UVJFTEs1c2YKR2JSYUpWWTk0U1J5K3IwenF0L2ptbjloNW1SckcxMW9Lb2w1ZnRZWGtyTHo2MWJDclltVFVHQjd4Q3JyL1lLUApVMmlqdnhQRnF1Y1Q2Q2trVjkwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEaTlwOEgwS3pJdlo5VWl1MXd0S3E5NXdiM3cKK1BUTk9ldDVRK0ZzdmRrY1RacHpmbU0xNGZsWDhPQS8zd2RLK0tPcGhSWU15c0lyTE5yQ3k0REhrUnhHaElJbAo3RDZPeDgvOUFUb0VhVXJ1a1FKMWJORWR0Q2ZicHBWYUlFYW9zYVJuZW9FdDgwREZWRUJqN1lWbDlISjlvODhRCjZXQXFQQnRPdVJ5ZDRKVDgrdjlQZU40RGlKejNQaTczRHdwYW9yb2U0aWdaUEtuK0FRS1Q3VURtWjBaNXR1RXoKOW9ieklRMzNObjdOZENpZEdTVUdGWFJOOUVPaUJNYlR6ai9VVFFnbDd3RWpXTGZXY0k0Y3MxNzhBV1pLYlIzbwp3U2R0OERSVlhlbTg0NnpYc0ZVb2tTQ2RWOGlmRmFzeTM0Zjd1enFoT01oN1UrRVdKdkFvakVXRUJaWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["tekton.dev"]
        apiVersions: ["v1beta1"]
        resources: ["pipelineruns"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    matchPolicy: Equivalent
